#spring:
#  data:
#    elasticsearch:
#      name: myes
#      #      cluster-nodes: 127.0.0.1:9300
#      nodes: hadoop137:9300,hadoop138:9300,hadoop139:9300


spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    #密码明文配置,一旦代码泄漏,数据不安全

    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    click:
#      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
#      url: jdbc:clickhouse://127.0.0.1:8123/default
#      initialSize: 10
#      maxActive: 100
#      minIdle: 10
#      maxWait: 6000

#可以读取,但是idea不能识别  在properties文件中可以识别
zhang1: mark1

#components
#  cache
#    enable: true
#
#components
#  cache: CacheManager

